#import "prelude.typ": *
#import "macros.typ": *
#import "glossaries.typ": *
#import "@preview/bookly:5.0.0": *
#import "@preview/retrofit:0.2.0": backrefs

#let revision = sys.inputs.at("revision", default: "working tree")

#show: backrefs.with(
  format: links => text(fill: rgb("666666"), size: 0.85em)[
    (Cited on #if links.len() == 1 { [p.] } else { [pp.] }
    #links.join(", ", last: " and "))
  ],
  read: path => read(path),
)
#show: bookly.with(
  title: "A Brief History of Compilers",
  author: "Asher Mancinelli",
  theme: classic,
  lang: "en",
  fonts: (
    size: 12pt,
    body: "Libertinus Serif",
  ),
  colors: (
    primary: rgb("245b8a"),
  ),
  title-page: {
    book-title-page(
      subtitle: none,
      edition: none,
      series: "Compiler History",
      institution: "A Brief History of Compilers",
      version-usage: [Revision #revision],
    )

    pagebreak()

    {
      set page(header: none, footer: none, numbering: none)
      set par(first-line-indent: 0pt)

      align(top + left)[
        #emph[
          This work is my own.
          Information derived from other sources or quoted is attributed.
          None of this text has been generated by artificial intelligence.
        ]
      ]

      pagebreak(to: "odd")
    }
  },
  config-options: (
    paper-size: "us-letter",
    open-right: true,
    alt-margins: false,
    par-indent: true,
  ),
)
#show: make-glossary
#register-glossaries()
#show: highlight-links

#show: front-matter

#{
  show outline: set heading(bookmarked: true)
  tableofcontents
}
// #tableofcontents

#show: main-matter

#include "chapters/preface.typ"
#include "chapters/read-instead.typ"
#include "chapters/intro.typ"
#include "chapters/dawn.typ"
#include "chapters/software.typ"
#include "chapters/freedom.typ"
#include "chapters/codesign.typ"
#include "chapters/quotes.typ"

#show: back-matter
#bibliography(
  "refs.bib",
  style: "chicago-author-date",
  full: true,
)

#print-glossaries()
