import '../../tools/justfile'

gen:
  just get-sections ./tracing/example-dsl.py
  python ./tracing/example-dsl.py > ./tracing/example-dsl-output.txt
  just get-sections ./tracing/example-dsl-output.txt
