#import "../../macros.typ": *
#import "../../glossaries.typ": *


#figure(
  [#table(columns: 3, inset: 5pt, stroke: 0.4pt,
  [Subproject],
  [Date Added],
  [Notes],
  [LLVM Core],
  [2000],
  [Project inception at UIUC, see #xref(<sec:lattner-llvm>, capital: true).],
  [Clang],
  [2006],
  [Chris starts work on Clang, see #xref(<sec:llvm-at-apple-clang>, capital: true).],
  [compiler-rt],
  [$tilde.op$2009],
  [Compiler runtime libraries, drop-in replacement for #mono-text("libgcc")],
  [Clang],
  [$tilde.op$2009],
  [Clang supports C and Objective-C.],
  [LLDB],
  [$tilde.op$2010],
  [LLDB shipped as part of Xcode 4.],
  [Clang++, libc++],
  [$tilde.op$2010],
  [Clang now supports C++; C++ standard library added as LLVM project.],
  [lld],
  [$tilde.op$2011--2015],
  [LLVM linker],
  [libclc],
  [$tilde.op$2012],
  [OpenCL standard library],
  [OpenMP runtime],
  [$tilde.op$2013--2014],
  [Added as LLVM's OpenMP runtime],
  [MLIR],
  [2019],
  [#todo[see section on MLIR]],
  [Flang],
  [2020],
  [#todo[see section on Flang]],
  [llvm-libc],
  [2020s],
  [],
)],
  kind: table,
  caption: [Approximate dates major LLVM subprojects joined the umbrella project.]
) <tab:lattner-llvm-project-timeline>

