#import "../../macros.typ": *
#import "../../glossaries.typ": *

== Tracing DSLs

AI kernel development typically requires the generation of lots of code specialized for specific
hardware and problem shapes and typical GPU programming models can make this difficult.
Prior to the popularization of tracing JITs, state of the art GPU programs were often written
using a CUDA C++ template library called CUTLASS #citen(<nvidia_cutlass_2023>),
which can have poor compile times and be difficult to use but can generate good
performance from relatively high level information.

While not the first tracing DSL, Tensorflow's DSL #citen(<agrawal2019tensorflow>)
is a useful example because we have a well-established corpus of open-source Tensorflow
code both with and without the tracing DSL.
JAX @JAX2018 and CuTe DSL (part of the CUTLASS project) are also popular
traced programming models #footnote[See also Guray Ozen's talk on CuTe DSL
@Ozen2025_CUTLASS_PythonDSL_CUTEDSL and the CuTe DSL documentation @NVIDIACUTLASSDocs.].

=== Staged Programming

Traced programming models involve several _stages_ where the user's program
is partially evaluated.
A single-stage Python program's evaluation semantics are typically
straightforward; the user runs `python ./program.py` and the program executes.
The simplest multi-stage programming model has two stages: first, the
user's program is executed and another program is #emph[generated by that program as a by
product], and in the second stage, that generated program is executed.
This is especially useful when developing GPU programs because the stages do not
need to evaluate in the same way. The user's program may first execute regular
Python code on the CPU, and the generated program may be a GPU kernel that needs
to be executed with a call to a driver library.

Most popular modern traced programming models are built in Python, so that is
what we will use for examples in this section.
These programming models typically provide a Python decorator that handles the
staging infrastructure.
In the first stage, the user's program is interpreted by the Python interpreter,
and the arguments to functions and GPU kernels are _symbolic_.
Operations performed on runtime values in the first stage operate on symbols
referring to the runtime arguments.
As the first stage is evaluated, operations on symbolic values become operations
in the generated #acr-long("ir").
The final #ir is the result of the first stage of evaluation.

The second stage involves compiling the #ir generated in the first stage of
evaluation into the native code for the target machine.
In the case of programming models targetting NVIDIA GPUs, this means the #ir is compiled
into PTX and then into the cubin format and then the kernel is launched using the CUDA driver api
// #footnote[Note that the driver api then JIT-compiles the PTX into SASS code!]
.

The staging decorator might look like this:

#code-file(path("./tracing/example_dsl.py"), lang: "python", region: "jit")

The jitted function might be called like this:

#code-file(path("./tracing/example0.py"), lang: "python", region: "scalar-kernel")

Note how the actual arguments are converted into symbolic values before being
passed into the function's first stage of execution.
Operations on these symbolic values are not performed in the first stage, but
are added to the #ir and evaluated in the second stage.
The #ir might look like this:

#code-file(path("./tracing/example0_output.txt"), lang: "python")

This _staged program_ would then be compiled to the target's native format where
the next stage of execution takes place.

Some tracing DSLs like CuTe DSL take this even further. Consider the following program:

#code-file(path("./tracing/example1.py"), lang: "python", region: "loop-kernel")

In which stage should the `for` loop be evaluated?
The loop bounds are all known during the first stage (`range(5)` does not depend
on any symbolic values) so the loop can be evaluated by the Python interpreter in the
first stage.
This is exactly what happens in our example DSL:

#code-file(path("./tracing/example1_output.txt"), lang: "python")

What about this kernel?

#code-file(path("./tracing/example2.py"), lang: "python", region: "loop-kernel-dyn")

The loop iterates over `range(N)` where `N` is a symbolic value.
What should happen in the first stage?
Without any special handling, our DSL would crash on this input:

#code-file(path("./tracing/example2_output.txt"), lang: "python")

Instead of using regular for-loops, we can use a decorated function that
determines whether the evaluation of the loop should happen in the first stage
or the second based on the type of the loop bounds.
Symbolic loop bounds will be turned into #ir and evalated in the second stage,
and static loop bounds will be evaluated in the first stage.

#code-file(path("./tracing/example3.py"), lang: "python", region: "dyn")
#code-file(path("./tracing/example3.py"), lang: "python", region: "static")
#code-file(path("./tracing/example3_output.txt"), lang: "python")

The `fori` decorator decides which stage the loop should be evaluated in:

#code-file(path("./tracing/example_dsl.py"), lang: "python", region: "for-decorator")

CuTe DSL#footnote[As of version 4.8, which is the latest version at the time of writing.]
handles this with a third stage of evaluation prior to running the program
in the Python interpreter.
The three stages of the CuTe DSL compiler are _pre-staging_ where the AST is preprocessed,
the _meta stage_ where the Python interpreter evaluates the program generated by the first stage,
and the _object stage_, where the #ir generated by evaluating the program from the first stage
is compiled into the native object format and executed on the GPU.
Guray Ozen describes this in detail in his LLVM Dev conference talk @Ozen2025_CUTLASS_PythonDSL_CUTEDSL.

Note that this AST-transformation stage is similar to macro-expansion in Lisp (#xref(<sec:lisp>)),
except Python does not have macros, so DSL designers must use decorators to
perform #acr-short("ast")-level transformations themselves without the help of the language.
#todo[example of similar model using lisp macros]

=== Why Is This Useful?

GPU kernel authors often care about different aspects of the programming model
at different points in the kernel authoring process.
In @Ozen2025_CUTLASS_PythonDSL_CUTEDSL, Guray makes these observations about
the priorities of kernel authors at NVIDIA:

- Fact 1: Fast GPU kernels are simple at runtime
	- No function calls
	- No object-oriented programming, polymorphism
	- No complex branching or deeply fused logic
- Fact 2: But developers love these concepts at authoring time
	- Meta-programming
	- Clean, structured Python code

Their priorites differ wildly based on the stage of the kernel authoring process
they are in.
It only makes sense, then, that the programming model would provide different
features based on the stage of the kernel authoring process.

#todo[debuggability. for example, add a python breakpoint inside the dynamic for
loop and show what the output looks like.]

/*
- Pre staging
- Meta stage
- Object stage

Pre-Staging - Python AST
• Inserts callbacks to capture program structure (e.g., control flow, loops, branches).
Meta-Stage - Python Interpreter
• Executes the meta program.
• During execution, callbacks emit MLIR IR (tracing + partial evaluation).
• Object-Stage - MLIR Compiler
• MLIR IR is lowered and compiled to a target binary.
• Runs on device (e.g., GPU/CPU/accelerator).
*/

#todo[ast rewriting]
