#import "../../macros.typ": *
#import "../../glossaries.typ": *

== Tracing DSLs

AI kernel development typically requires the generation of lots of code specialized for specific
hardware and problem shapes and typical GPU programming models can make this difficult.
Prior to the popularization of tracing JITs, state of the art GPU programs were often written
using a CUDA C++ template library called CUTLASS #citen(<nvidia_cutlass_2023>),
which can have poor compile times and be difficult to use but can generate good
performance from relatively high level information.

While not the first tracing DSL, Tensorflow's DSL #citen(<agrawal2019tensorflow>)
is a useful example because we have a well-established corpus of open-source Tensorflow
code both with and without the tracing DSL.
JAX @JAX2018 and CuTe DSL (part of the CUTLASS project) are also popular
traced programming models #footnote[See also Guray Ozen's talk on CuTe DSL
@Ozen2025_CUTLASS_PythonDSL_CUTEDSL and the CuTe DSL documentation @NVIDIACUTLASSDocs.].

=== Staged Programming

Traced programming models involve several _stages_ where the user's program
is partially evaluated.
A single-stage Python program's evaluation semantics are typically
straightforward; the user runs `python ./program.py` and the program executes.
The simplest multi-stage programming model has two stages: first, the
user's program is executed and another program is #emph[generated by that program as a by
product], and in the second stage, that generated program is executed.
This is especially useful when developing GPU programs because the stages do not
need to evaluate in the same way. The user's program may first execute regular
Python code on the CPU, and the generated program may be a GPU kernel that needs
to be executed with a call to a driver library.

Most popular modern traced programming models are built in Python, so that is
what we will use for examples in this section.
These programming models typically provide a Python decorator that handles the
staging infrastructure.
In the first stage, the user's program is interpreted by the Python interpreter,
and the arguments to functions and GPU kernels are _symbolic_.
Operations performed on runtime values in the first stage operate on symbols
referring to the runtime arguments.
As the first stage is evaluated, operations on symbolic values become operations
in the generated #acr-long("ir").
The final #ir is the result of the first stage of evaluation.

The second stage involves compiling the #ir generated in the first stage of
evaluation into the native code for the target machine.
In the case of programming models targetting NVIDIA GPUs, this means the #ir is compiled
into PTX and then into the cubin format and then the kernel is launched using the CUDA driver api
// #footnote[Note that the driver api then JIT-compiles the PTX into SASS code!]
.

The staging decorator might look like this:

```python

```

```python
@jit
def kernel(a, b, c):
    a[0] = a[0] + b[0] * c[0]

a, b, c = # create torch tensors...
kernel(a, b, c)
```

